// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// slopeProx
arma::mat slopeProx(const arma::mat& beta, const arma::vec& lambda, const double shrinkage);
RcppExport SEXP _pengen_slopeProx(SEXP betaSEXP, SEXP lambdaSEXP, SEXP shrinkageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type shrinkage(shrinkageSEXP);
    rcpp_result_gen = Rcpp::wrap(slopeProx(beta, lambda, shrinkage));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pengen_slopeProx", (DL_FUNC) &_pengen_slopeProx, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pengen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
